### ISSUE TITLE
Swashbuckle CLI lacks support for minimal APIs with .NET 6

### ISSUE THREAD

**Issue by bradygaster** [domaindrivendev/Swashbuckle.AspNetCore#2168]
We're trying out various Swashbuckle-enabled scenarios with the upcoming [Minimal APIs](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/#introducing-minimal-apis) feature, and noted that it appears to not work out-of-the-gate with the new style of development. 

I created a basic minimal API, then added Swashbuckle to it and got both the OpenAPI description and Swagger UI working using the following code with the RC1 preview bits. 

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c => 
{
    c.SwaggerDoc("v1", new Microsoft.OpenApi.Models.OpenApiInfo
    {
        Title = "Minimal API",
        Version = "v1"
    });
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.MapGet("/", () => "Hello World!");

app.Run();
```

Things work fine in the "run" scenario. Yet, when I execute the CLI command as such:

```
swagger tofile --host https://localhost:5001 MinimalWithSwashbuckle.dll v1
```

I get an error indicating that the code would need a `Startup` class to interrogate to work. 

```
Unhandled exception. System.InvalidOperationException: A type named 'StartupProduction' or 'Startup' could not be found in assembly 'MinimalWithSwashbuckle'.
   at Microsoft.AspNetCore.Hosting.StartupLoader.FindStartupType(String startupAssemblyName, String environmentName) in Microsoft.AspNetCore.Hosting.dll:token 0x6000136+0x14c
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors) in Microsoft.AspNetCore.Hosting.dll:token 0x6000189+0x2de
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass14_2.<BuildCommonServices>b__5(IServiceProvider _) in Microsoft.AspNetCore.Hosting.dll:token 0x6000289+0x0
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000094+0x0
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) in Microsoft.Extensions.DependencyInjection.dll:token 0x60000a6+0x23
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context) in Microsoft.Extensions.DependencyInjection.dll:token 0x600008e+0x61
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) in Microsoft.Extensions.DependencyInjection.dll:token 0x60000a5+0x4e
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope) in Microsoft.Extensions.DependencyInjection.dll:token 0x600008b+0x26
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000068+0x38
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) in System.Collections.Concurrent.dll:token 0x60000d3+0x4f
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000066+0xd
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000061+0x0
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider) in Microsoft.Extensions.DependencyInjection.Abstractions.dll:token 0x6000094+0xe
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureStartup() in Microsoft.AspNetCore.Hosting.dll:token 0x600014b+0x9
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices() in Microsoft.AspNetCore.Hosting.dll:token 0x600014a+0x8
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize() in Microsoft.AspNetCore.Hosting.dll:token 0x6000147+0x0
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build() in Microsoft.AspNetCore.Hosting.dll:token 0x6000188+0x9a
   at Swashbuckle.AspNetCore.Cli.Program.GetServiceProvider(Assembly startupAssembly) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 133
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 72
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 111
```

**Comment by bradygaster** [comment]
@domaindrivendev I was chatting with @captainsafia @brennanconroy and @davidfowl about this and we're prepared to create a PR but just wanted to make sure we know what you'd expect. Proposing a list below. 

* [ ] actual coding work completed to fix the issue 
* [ ] updates to docs in *this* repository (like the `readme.md`, etc.) if there are any impacts to existing use cases that impact existing customers
* [ ] tests to make sure the existing scenario (Web API with Controllers with .NET Core) continue to work
* [ ] tests to make sure the new scenario (minimal APIs) work

Let us know if this is accurate and we'll get on it. As well, we'd like to know an expectation on turnaround time once the PR comes in as we're trying to ready this against other items and would appreciate it if you could give us an expectation. 

As always, we appreciate the support.

**Comment by domaindrivendev** [comment]
Sounds good @bradygaster 👍

**Comment by stevenknox** [comment]
Is there a temporary workaround for this to start generating clients again for Net 6 Minimal APIs?

**Comment by davidfowl** [comment]
It should work now

**Comment by jvos-priva** [comment]
I am already using 6.2.3 and this all used to work until I added the following line in my code, after which it failed with the same exception as mentioned by the original poster:

``` csharp
builder.Configuration.AddAzureKeyVault(
        new Uri($"https://{builder.Configuration["keyvault:name"]}.vault.azure.net/"),
        new DefaultAzureCredential());
```

I am using .NET 6 top level statements template but with a full blown API. Does anyone have any ideas?

**Comment by jvos-priva** [comment]
After some digging I figured out the problem. Even though the error is the same, the root cause is unrelated. I'll create a separate issue for it and link it here after I have done so.

**Comment by julealgon** [comment]
I just ran into this exact same problem and I'm _not_ using minimal APIs: this appears to be an issue related to the simplified top-level program setup.

Upon running the cmd against my DLL, I get an error instantaneously:

```
dotnet swagger tofile --output c:\sample.json {pathToMyAssembly} v1
```

```
Unhandled exception. System.InvalidOperationException: A type named 'StartupProduction' or 'Startup' could not be found in assembly '{myAssembly}'.
   at Microsoft.AspNetCore.Hosting.StartupLoader.FindStartupType(String startupAssemblyName, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass14_2.<BuildCommonServices>b__5(IServiceProvider _)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Swashbuckle.AspNetCore.Cli.Program.GetServiceProvider(Assembly startupAssembly) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 145
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_4(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 82
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 121
```
Just to see what would happen, I created an empty `Startup` class somewhere with a void `Configure` method. Then, this is what I get after running the command again (seems like it really is looking for a startup class there):
```
Unhandled exception. System.InvalidOperationException: No service for type 'Swashbuckle.AspNetCore.Swagger.ISwaggerProvider' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_4(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 82
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 121
```

I'm using version 6.3.1 of the CLI package.

I need to obtain the swagger doc during my pipeline build to update Azure API Management. Any help is appreciated.

**Comment by davidfowl** [comment]
Is everything updated to the latest? .NET 6 and swashbuckle?

**Comment by average04** [comment]
Updated to the latest. It's working now, Thanks a lot

**Comment by average04** [comment]
> Is everything updated to the latest? .NET 6 and swashbuckle?

Updated to the latest. It's working now, Thanks a lot

**Comment by boukeversteegh** [comment]
This is a very confusing error. In my real problem was also unrelated, just an error while launching swagger with a different environment (missing config values).

Assume that the problem is not with swagger:

- check that the app can launch
- check that it can launch with the environment setting you use for swagger

**Comment by deivyd321** [comment]
The issue still occurs with .NET 6. Created a very simple .NET 6 API with swagger. All nuggets are the latest. And created a default publish profile with GitHub actions.

It fails in step: Generate open api specification

Here's the error:
Run swagger tofile --output "X/publish/swagger.json" "SimpleIp/bin/Release/net6.0/X.dll" "v1"
Unhandled exception. System.InvalidOperationException: A type named 'StartupProduction' or 'Startup' could not be found in assembly 'SimpleIp'.
   at Microsoft.AspNetCore.Hosting.StartupLoader.FindStartupType(String startupAssemblyName, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass14_2.<BuildCommonServices>b__5(IServiceProvider _)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Swashbuckle.AspNetCore.Cli.Program.GetServiceProvider(Assembly startupAssembly) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 1[33](https://github.com/deivyd321/SimpleIp/actions/runs/3756652695/jobs/6382960137#step:10:34)
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 72
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 111
Error: Process completed with exit code 1[34]

**Comment by OpenSpacesAndPlaces** [comment]
Should this thread be closed? Running into the same issues on .Net 7.0
```
System.InvalidOperationException: A type named 'Startuplocalhost' or 'Startup' could not be found in assembly 'MarketCarpenter-6'.
   at Microsoft.AspNetCore.Hosting.StartupLoader.FindStartupType(String startupAssemblyName, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.ScanAssemblyAndRegisterStartup(ServiceCollection services, String startupAssemblyName)
```

**Comment by bradygaster** [comment]
cc @captainsafia FYI

**Comment by nkoudelia** [comment]
The `dotnet new webapi` command creates a project file with an outdated `Swashbuckle.AspNetCore` reference. That's where the error is coming from. Just updated it to the same version with the tool (6.5.0 atm.) and everything is working fine.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>web_api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>

</Project>
```

**Comment by captainsafia** [comment]
> The `dotnet new webapi` command creates a project file with an outdated `Swashbuckle.AspNetCore` reference. That's where the error is coming from. Just updated it to the same version with the tool (6.5.0 atm.) and everything is working fine.
> 
> 
> 
> ```xml
> 
> <Project Sdk="Microsoft.NET.Sdk.Web">
> 
> 
> 
>   <PropertyGroup>
> 
>     <TargetFramework>net6.0</TargetFramework>
> 
>     <Nullable>enable</Nullable>
> 
>     <ImplicitUsings>enable</ImplicitUsings>
> 
>     <RootNamespace>web_api</RootNamespace>
> 
>   </PropertyGroup>
> 
> 
> 
>   <ItemGroup>
> 
>     <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
> 
>   </ItemGroup>
> 
> 
> 
> </Project>
> 
> ```

@nkoudelia Can you open a bug on the ASP.NET Core repo for this? We can see about patching the 6.0 templates to pick up the fixed package version.

**Comment by akshay-zz** [comment]
Even though I'm using `"Swashbuckle.AspNetCore" Version="6.5.0"` and having a tool version 6.5.0 I'm getting the error.
`Unhandled exception. System.InvalidOperationException: A type named 'StartupProduction' or 'Startup' could not be found in assembly 'Presentation.WebApi'`

**Comment by bryanjtc** [comment]
Any update on this?

**Comment by captainsafia** [comment]
I've opened https://github.com/dotnet/aspnetcore/pull/47860 to update the version of the package referenced in the .NET 6 templates to the latest release. This should resolve the issue. If there are any problems happening that _aren't_ resolved by updating the latest version, filing an ew issue would be helpful so we can track it down.

**Comment by Patrick-Davis-MSFT** [comment]
This also should be updated in the GitHub Actions template under the environment variable SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 

Set it to 6.5.0 if anyone is looking for the solution to the same issue running GitHub actions.

**Comment by MortenMeisler** [comment]
> I just ran into this exact same problem and I'm _not_ using minimal APIs: this appears to be an issue related to the simplified top-level program setup.
> 
> Upon running the cmd against my DLL, I get an error instantaneously:
> 
> ```
> dotnet swagger tofile --output c:\sample.json {pathToMyAssembly} v1
> ```
> 
> ```
> Unhandled exception. System.InvalidOperationException: A type named 'StartupProduction' or 'Startup' could not be found in assembly '{myAssembly}'.
>    at Microsoft.AspNetCore.Hosting.StartupLoader.FindStartupType(String startupAssemblyName, String environmentName)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass14_2.<BuildCommonServices>b__5(IServiceProvider _)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
>    at Microsoft.AspNetCore.Hosting.WebHost.EnsureStartup()
>    at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
>    at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at Swashbuckle.AspNetCore.Cli.Program.GetServiceProvider(Assembly startupAssembly) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 145
>    at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_4(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 82
>    at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
>    at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
>    at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 121
> ```
> 
> Just to see what would happen, I created an empty `Startup` class somewhere with a void `Configure` method. Then, this is what I get after running the command again (seems like it really is looking for a startup class there):
> 
> ```
> Unhandled exception. System.InvalidOperationException: No service for type 'Swashbuckle.AspNetCore.Swagger.ISwaggerProvider' has been registered.
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_4(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 82
>    at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
>    at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
>    at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 121
> ```
> 
> I'm using version 6.3.1 of the CLI package.
> 
> I need to obtain the swagger doc during my pipeline build to update Azure API Management. Any help is appreciated.
> 
> EDIT:
> 
> As per what @jvos-priva above mentioned, it appears that exceptions in the setup are causing this package to raise unrelated errors.... after adding `System.Diagnostics.Debugger.Launch` to my startup, I can see it is trying to obtain production settings and throwing a `InvalidOperationException`.
> 
> It seems to be hosting the API in default `production` mode, which causes `appsettings.Production.config` to be read... my app doesn't have all production settings in that file, some of the settings come through the hosting environment through environment variables in Azure.
> 
> How am I supposed to run this without forcing `production` mode? I don't see any flags in the tool help to change it.
> 
> EDIT 2:
> 
> Ok, I made it work by temporarily replacing a `configuration.GetRequiredSection` call with `configuration.GetSection`. After that, it was a only a matter of running the tool from the correct folder and it worked. I was running the tool from the solution root instead of the actual API project root, meaning it wasn't even loading my `appsettings.json` properly and causing other errors (I assume it hosts considering the callsite as the main folder, so if no config files exist at that level, nothing is loaded).
> 
> Not happy with the fact that I had to make my code more brittle however... the `GetRequiredSection` call was there for a purpose: to warn me in case configuration values were missing during startup. Oh well... I'll have to rethink some of this.

This was exactly my problem.

2 workarounds:
1) As you suggested, use GetSection instead of GetRequiredSection
2) Create a appsettings.Production.json file (appsettings.Prod does not work)

This is a bit clunky either way, I would expect alot of people want to use GetRequiredSection in their Program.cs

It's the same issue with Nswag btw.

**Comment by backfromexile** [comment]
Why is this issue closed?
This issue still persists using the latest versions (6.5.0) of both the CLI package and the ASP.NET Core package on .NET 7.0

**Comment by sapineau** [comment]
Sorry to lay it on thick. it is for a roadmap question.

I've been in this exact situation of this thread on .net 7.0.

As mentionned earlier, we have implemented `Startup.cs` and `Program.cs` as it was on .net core 3.1 (see below).

```csharp
    public class Startup
    {
        public IConfiguration Configuration { get; }
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            // Add services to the container.
            services.AddControllers();

            //Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
            services.AddEndpointsApiExplorer();
            services.AddSwaggerGen(option =>
            {
                // Use options as you need
            });
        }

        public void Configure(WebApplication app, IWebHostEnvironment env)
        {
           // Do thing
        }
    }
```

I've seen that in 2019 [sverrirs](https://github.com/sverrirs) explain another way to resolve this issue :  https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/356#issuecomment-566449902

I think a lot of person fall in this same issue (that have solutions, as mention on this thread and https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/356 thread).

Is there a roadmap to resolve this issue without add extra code ?

Thanks.
Samuel

**Comment by MitchellW-DWL** [comment]
Don't suppose there's any movement on this? I'm still seeing it on 6.5.0 and 6.8.0 with .net8

**Comment by martincostello** [comment]
@MitchellW-DWL https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2168#issuecomment-1520497113
