### ISSUE TITLE
Paths with colon causes "Failed to load API definition." error.

### ISSUE THREAD

**Issue by marekzyla** [domaindrivendev/Swashbuckle.AspNetCore#2327]
Version: **6.2.3**
Frequency: Always

### Error description

As we want to follow the rules to add colons when the action is making non CRUD operation, due to recommendations here: https://cloud.google.com/apis/design/custom_methods

We are experiencing issue with generation of Swagger documentation. The problem is not occueing in version **5.6.3** and we can successfully use this version.

### Example

```c#
 [HttpPut("{id}:Example")]
public async Task<IActionResult> Example(string id)
{
...
}
```

The swagger UI cannot be generated for this:

![image](https://user-images.githubusercontent.com/18402527/151953638-ca0b7b2b-a1a2-4a9b-b54f-d0eb9759141d.png)

**Comment by domaindrivendev** [comment]
Dup of #2239 and fixed by #2310. Nuget release on it's way!

**Comment by RodrigoPrandi** [comment]
was this error resolved?

I'm on the latest version and the problem still persists.

![image](https://user-images.githubusercontent.com/10632714/155405004-d32bc662-0601-4dfe-a6d1-9a61bbbad6b5.png)


![image](https://user-images.githubusercontent.com/10632714/155404785-66fac176-646d-47fa-aaa2-57b807b89a8a.png)

**Comment by RodrigoPrandi** [comment]
@marekzyla  the issue has been resolved in release 6.3.0

**Comment by marekzyla** [comment]
I can confirm it's solved. Thanks!
