### ISSUE TITLE
Add support for OpenAPI 3.0.4

### ISSUE THREAD

**Issue by swurzinger** [domaindrivendev/Swashbuckle.AspNetCore#3265]
The integrated SwaggerUI currently doesn't support OpenAPI 3.0.4

This has been recently fixed in [SwaggerUI 5.19.0](https://github.com/swagger-api/swagger-ui/releases/tag/v5.19.0):
https://github.com/swagger-api/swagger-ui/pull/10247

Thus SwaggerUI dependency should be updated to v5.19.
Other than that Open 3.0.4 seems to work just fine with Swashbuckle.

**Comment by martincostello** [comment]
Dependabot will automatically generate a PR tomorrow, and then it will be included in our next release:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/3c64558cf3e83fb827e869bb80f8af1b6ea050d6/.github/dependabot.yml#L17-L23

**Comment by martincostello** [comment]
For some reason dependabot didn't run today as configured to. I've manually run it.

The change to update SwaggerUI will go out when we next do a release.

**Comment by martincostello** [comment]
Resolved by #3266.

**Comment by HenryZhang-ZHY** [comment]
When will 7.3.0 be released?

**Comment by martincostello** [comment]
After #3263 is completed.

**Comment by martincostello** [comment]
Fixed in [Swashbuckle.AspNetCore.SwaggerUI 7.3.0](https://www.nuget.org/packages/Swashbuckle.AspNetCore.SwaggerUI/7.3.0).

**Comment by jmanico** [comment]
Why did you close this? This is doing a lot of damage to the ecosystem. This is not fixed in 7.3!

Please re-open!

**Comment by jmanico** [comment]
> Fixed in [Swashbuckle.AspNetCore.SwaggerUI 7.3.0](https://www.nuget.org/packages/Swashbuckle.AspNetCore.SwaggerUI/7.3.0).

This has not been fixed in 7.3

**Comment by martincostello** [comment]
Is what you're saying is that swagger-ui 5.19.0 didn't fix the problem that it doesn't understand version 3.0.4 that Microsoft.OpenApi emits?

If that's the case there's nothing we can do until there's a swagger-ui version that does fix it.

If that isn't the case, then please explain how it isn't fixed, because the underlying issue was a problem in swagger-ui exposed by a change in Microsoft.OpenApi 1.6.23 that was supposed to be fixed by swagger-ui 5.19.0.

Swashbuckle depends on Microsoft.OpenApi 1.6.22, so something else has to have updated the version in your dependency graph to 1.6.23, and we just redistribute swagger-ui.

**Comment by MattAllen-Alaska** [comment]
I was working with @jmanico when he posted that,  I pulled both Microsoft.OpenApi 1.6.23 and Swashbuckle 7.3 today and Continued to get the same "Unable to render this definition" error on the swagger page.  The error does go away with Microsoft.OpenApi 1.6.22 so it does appear the issue is still around the Version 3.0.4 for OpenApi.  If the issue is verified fixed in Swagger 5.19 then perhaps 5.19 did not get fully included with Swashbuckle 7.3.  Either way the issue itself is not currently resolved.  It may need to wait for an update from Swagger and so it may not be waiting on dev work from Swashbuckle, but it is still an open issue awaiting an update from a dependent library.

**Comment by martincostello** [comment]
It works exactly as expected from my testing with this commit: https://github.com/martincostello/aspnetcore-openapi/commit/7bcf1c7914d9ac6405dcf16468bbabc6d3d91240

It uses:

- Swashbuckle.AspNetCore.SwaggerUI 7.3.0 (which bundles swagger-ui 5.19.0)
- Microsoft.OpenApi 1.6.23 (which returns an OpenAPI document with a version of 3.0.4)

Running the app and browsing to `https://localhost:50001/swagger/index.html` correctly renders the UI:

![Image](https://github.com/user-attachments/assets/0ab5ca15-a842-4f38-83c5-e2c83a0a0a8d)

Downgrading to 6.2.0 shows the error fixed by https://github.com/swagger-api/swagger-ui/pull/10247.

**Comment by martincostello** [comment]
All I'll say from my testing is that I had to force refresh the browser to clear the cache. Try doing that.

I cannot replicate a problem with the given fixed configuration, so I consider this issue to be fixed in that we have published a new version with the absolute latest version of swagger-ui in it, so any issue is a separate distinct issue that needs to be fixed upstream.

If you can provide a minimal reproducible issue that shows that there's an issue with **this library**, then I'll look into it further.
