### ISSUE TITLE
Configure oAuth on SwaggerUI3

### ISSUE THREAD

**Issue by imperugo** [domaindrivendev/Swashbuckle.AspNetCore#591]
Hi, 
I'm testing the preview of the following packages:

```
<PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="1.2.0-preview-0285" />
<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="1.2.0-preview-0285" />
<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI3" Version="1.2.0-preview-0285" />
```

It seems to work well, except for the oAuth integration.
I can configure it (and I see the output on the page)

```
var oAuth2Scheme = new OAuth2Scheme();
oAuth2Scheme.AuthorizationUrl = urlBuilderConfiguration.Auth.Url + "/connect/authorize";
oAuth2Scheme.Flow = "implicit";
oAuth2Scheme.TokenUrl = urlBuilderConfiguration.Auth.Url + "/connect/authorize";
oAuth2Scheme.Scopes = new ConcurrentDictionary<string, string>();
oAuth2Scheme.Scopes.Add(new KeyValuePair<string, string>("admin", "Admin APIs access."));
oAuth2Scheme.Scopes.Add(new KeyValuePair<string, string>("www", "Www APIs access."));
oAuth2Scheme.Scopes.Add(new KeyValuePair<string, string>("input", "Input APIs access."));

options.AddSecurityDefinition("Bearer", oAuth2Scheme);
```

But I can't configure the client into `UseSwaggerUI3`.

With the previous version I was able to do something like that

```
options.ConfigureOAuth2("ClientID", "ClientSecret", "swagger-ui-realm", "API Swagger UI");
```

Now?
Any hint?

Thanks

**Comment by domaindrivendev** [comment]
Resolved by 1f217e513e66c7b122007058447fee0e26b9eaa0 and ff61147fedb50bf5ed87249f3f8a132e1b303b80. Will be available with 2.0.0 package which is coming to Nuget in the next week or so.

**Comment by Monte-Christo** [comment]
Sorry for my ignorance, but I am still unable to access ConfigureOAuth2. I am told it does not exist in SwaggerUIOptions. Here is my code in The Configure() method of my Startup class:

app.UseSwaggerUI(c =>
{
c.SwaggerEndpoint("/swagger/v1/swagger.json", "Library API V1");
c.ConfigureOAuth2("implicit", "secret", "swagger-ui-realm", "Swagger UI");
});

Here are my NuGet references:

<itemgroup>
<packagereference include="AspNetCoreRateLimit" version="2.1.0"/>
<packagereference include="AutoMapper" version="7.0.1"/>
<packagereference include="IdentityServer4.AccessTokenValidation" version="2.6.0"/>
<packagereference include="Marvin.Cache.Headers" version="3.0.0-beta"/>
<packagereference include="Microsoft.AspNetCore.All" version="2.1.3"/>
<packagereference include="Microsoft.VisualStudio.Web.CodeGeneration.Design" version="2.1.3"/>
<packagereference include="NLog.Web.AspNetCore" version="4.6.0"/>
<packagereference include="Serilog.Sinks.File" version="4.0.0"/>
<packagereference include="Swashbuckle.AspNetCore" version="3.0.0"/>
<packagereference include="Swashbuckle.AspNetCore.SwaggerUI" version="3.0.0"/>
<packagereference include="System.Linq.Dynamic.Core" version="1.0.8.16"/>
</itemgroup>

Any idea what I am missing?

**Comment by Monte-Christo** [comment]
Well, i found the answer myself, finally. The ConfigureOAuth2 method is superseded by individual setting methods:

app.UseSwaggerUI(c =>
{
...
c.OAuthClientId("test-id");
c.OAuthClientSecret("test-secret");
c.OAuthRealm("test-realm");
c.OAuthAppName("test-app");
c.OAuthScopeSeparator(" ");
c.OAuthAdditionalQueryStringParams(new { foo = "bar" });
c.OAuthUseBasicAuthenticationWithAccessCodeGrant();
});

See https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements
