### ISSUE TITLE
Swagger route direct with 2.4.0

### ISSUE THREAD

**Issue by RomainWilbert** [domaindrivendev/Swashbuckle.AspNetCore#678]
Hi ! 
Since 2.4.0 upgrade, When I access Swagger route (xxx/docs/rest), I am redirected to docs/docs/rest.
If I add a "/" at the end (xxx/docs/rest/) then it works fine. 
Is this normal ?
Here is my config in Startup : 
`            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger(c => { c.RouteTemplate = "docs/rest/{documentName}/swagger.json"; });

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.), specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/docs/rest/v1/swagger.json", "v1");
                c.DocumentTitle = ApiName;
                c.RoutePrefix = "docs/rest";
            });`

**Comment by domaindrivendev** [comment]
There was a change to some redirect logic but shouldn’t have broken existing stuff. Will investigate and revert

**Comment by domaindrivendev** [comment]
Should be fixed by the following commit - b84ecc20448f6b8db73c13786a488c890c848145. Could you pull down the preview package from myget.org (https://myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore) and try it out?

**Comment by RomainWilbert** [comment]
I still have the issue with the preview.
I must say that I only reproduce this bug on my development server. My app is a docker app build from microsoft/aspnetcore.
When I run the app on localhost in VS code or in docker, it works fine.

**Comment by domaindrivendev** [comment]
You may need to clear browser cache or just try again in an incognito window. The old incorrect redirect may still be cached in your browser

**Comment by RomainWilbert** [comment]
thanks for the tip but the problem is persistent.

**Comment by domaindrivendev** [comment]
Hmmm it’s working for me with your exact setup so not sure what else I can do at this point. Perhaps you could try with a new project from scratch just to see if it still repros? Also confirm you def have the latest preview version

**Comment by doctorless** [comment]
I'm having the same problem. Also tried the preview and had the same issue.

**Comment by domaindrivendev** [comment]
@doctorless - did you use an ingognito window when you tried the preview?

**Comment by doctorless** [comment]
@domaindrivendev I tried an incognito window, a different browser, and even a different device on a different network that had never seen the endpoint before.

**Comment by domaindrivendev** [comment]
Ok I need a repro before I can help. Could someone here put together exact repro steps, starting from a blank project and also including browser being used. Bonus points for http activity (e.g. via browser developer tools).

**Comment by doctorless** [comment]
It works fine from localhost; it's about as simple as a swagger can get:

in Configure:
```            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "API v1");
            });```

in ConfigureServices:
```            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Swashbuckle.AspNetCore.Swagger.Info { Title = "API", Version = "v1" });
                c.IncludeXmlComments(Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "API.xml"));
            });```

I publish this as a lambda on AWS, which is then routed via API Gateway. Trying to visit /swagger/ leads to /swagger/swagger/

**Comment by doctorless** [comment]
```curl 'https://path.to.api/swagger/' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36' --compressed -v```

returns

```
* timeout on name lookup is not supported
*   Trying ip.of.aws.server...
* Connected to path.to.api (ip.of.aws.server) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4564 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.to.api
*  start date: Apr 11 00:00:00 2018 GMT
*  expire date: May 11 12:00:00 2019 GMT
*  subjectAltName: host "path.to.api" matched cert's "*.to.api"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* TCP_NODELAY set
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x269a510)
} [5 bytes data]
> GET /swagger/ HTTP/1.1
> Host: path.to.api
> Accept: */*
> Accept-Encoding: deflate, gzip
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
>
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
} [5 bytes data]
< HTTP/2.0 301
< date:Thu, 12 Apr 2018 23:28:03 GMT
< content-type:application/json
< content-length:0
< location:swagger/
< x-amzn-requestid:***
< x-amz-apigw-id:====
< x-amzn-trace-id:sampled=0;root=1-***
<
* Connection #0 to host path.to.api left intact
```

**Comment by doctorless** [comment]
After digging deeper, I see the reason this issue is occurring for me, and perhaps why it may be occurring for @RomainWilbert. I use API Gateway, which apparently strips the trailing slash from proxied URLs before handing them off to the destination server (https://forums.aws.amazon.com/message.jspa?messageID=749625). It can't be configured not to when using the proxy. As a consequence, it will always send a request to the API server as `/swagger` rather than `/swagger/`. Consequentially, I run into the redirect check regardless of how the URL was actually formed from the browser/curl/etc. That redirect is served back to me as `Location: swagger/`. Because I actually had requested `/swagger/`, it just appends the location provided to the end of that URL. Is there perhaps a way we can avoid the need for a terminal slash for the Swagger UI middleware?

**Comment by domaindrivendev** [comment]
@RomainWilbert - are you using AWS Gateway too?

**Comment by RomainWilbert** [comment]
No, just dockerized kestrel

Le ven. 13 avr. 2018 à 18:01, Richard Morris <notifications@github.com> a
écrit :

**Comment by domaindrivendev** [comment]
@RomainWilbert & @doctorless - I've just implemented a slightly different approach (see d2df21d76671eff87ce34f141f55c737249f0e28) that might help with this issue. I think it will definitely help @doctorless, not sure about @RomainWilbert because the root cause there still isn't clear to me.

Perhaps you could both try the latest preview (Swashbuckle.AspNetCore.2.4.0-preview-0463) and let me know if it makes a difference?

**Comment by stambler** [comment]
@domaindrivendev thank you.  I have been attempting something similar--generating Swagger UI using Swashbuckle in an ASP.NET Core Web API running in an AWS Lambda.  Yesterday I cloned and built locally the pull request from @doctorless  and that worked.  Today I tried your NuGet package from your MyGet site and that worked also.
Thank you @doctorless and @domaindrivendev !

**Comment by domaindrivendev** [comment]
@RomainWilbert, @doctorless - I'm closing this as @stambler's response plus my own observations point to a valid resolution.

**Comment by domaindrivendev** [comment]
Feel free to re-open if you have information to prove otherwise

**Comment by virzak** [comment]
@domaindrivendev hello,

Even with the latest 2.4.0-preview-0465 /swagger is redirected to /swagger/swagger/ for me.

**Comment by domaindrivendev** [comment]
@virzak is there any chance you could create a set of repro steps starting from an empty project?

**Comment by virzak** [comment]
@domaindrivendev 

Steps to create AWS account and install Visual Studio plugin are skipped.

Create AWS Serverless Application (.NET Core)
Select ASP.NET Core Web API
Run and navigate to: /api/values
Add Swashbuckle.AspNetCore and Swashbuckle.AspNetCore.Swagger 2.4.0-preview-0465 from feed https://www.myget.org/F/domaindrivendev/api/v3/index.json
Go through steps 2-5
Run and navigate to: /swagger
Ensure it shows S3Proxy and Values controller methods
Publish to AWS Lambda.
Navigate to https://{key}.execute-api.{region}.amazonaws.com/Prod/api/values and ensure it works

Change URL to https://{key}.execute-api.{region}.amazonaws.com/Prod/swagger
*ERROR* Failed to load API definition. Fetch error - undefined /swagger/v1/swagger.json

Try trailing slash
Change URL to https://{key}.execute-api.{region}.amazonaws.com/Prod/swagger/
*ERROR* redirected to https://{key}.execute-api.{region}.amazonaws.com/Prod/swagger/swagger/index.html

**Comment by mross002** [comment]
Also having issue if leave off trailing slash when using netCore 2.0.3, even when debugging locally, or in my stage or prod environment which is setup as a reverse proxy.  Downgraded to swashbuckle 2.3.0 and the issue goes away, will wait for the next release to upgrade.

**Comment by domaindrivendev** [comment]
@mross002 - could you provide a set of repro steps starting from an empty project? I can now see why the latest fix still won’t work with AWS Gateway (it’s their bug) but it should def work in a local project

**Comment by domaindrivendev** [comment]
For the API Gateway problem, I’m going to provide a config option for working around the problem

**Comment by mross002** [comment]
Sure, so the issue occurs when routePrefix contains multiple paths, I have it set to “api/docs/v1”, on 2.4.0 along with a custom indexStream set to an embedded resource. if I go to localhost/api/docs/v1/ (with slash), all is good), if I go to localhost/api/docs/v1 (no slash) I get automatically redirected to localhost/api/docs/api/docs/v1/ with a 301 moved permanently.  It seems each additional folder in routePrefix gets duplicated in the redirect (i.e. api/docs gets included in the url twice). I’ve tried changing and re-ordering all the middleware I’m enabling, useStaticFiles, useDefaultFiles, etc., tried routeOptions trailingSlash Settings, etc. no luck, only thing that resolved the issue was downgrading to 2.3.0.

**Comment by domaindrivendev** [comment]
The main bug fix hasn't been published to the official feed, it's only available as a preview package on myget.org. Can you try it with the following:

https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore

Thanks

**Comment by virzak** [comment]
The bug is still there and the output is exactly the same as before.

As a side note, why is the preview version number is 2.4.0 and not 2.4.1 or 2.5.0? When my package source is set to "All", it wants to "upgrade" to 2.4.0 even though that's an older version.

![image](https://user-images.githubusercontent.com/6209775/39780320-f09b0b70-52d9-11e8-8cfa-6e585519f117.png)

**Comment by mross002** [comment]
@domaindrivendev - thanks for looking into this, I installed the preview package but the issue persists, still redirects to http://localhost/api/docs/api/docs/v1/.  I haven't tried all the different fixes / work-arounds I did yesterday, like messing with Routing and MvC settings, but they didn't solve the issue anyway, the redirect / 301 Moved Permanently was occurring very early in the Middleware pipeline before any of those middleware fixes could make a difference.

**Comment by domaindrivendev** [comment]
At this point I have applied a change that I believe _should_ fix this issue. I can't repro locally, so if folks are still having issues I would encourage them to pull down the source code and start debugging to get to the bottom of it. If you have a repro and can find a root cause, let me know and I'll re-open the issue.

In the meantime, you can put a fairly simple change in place to perform the shortcut-to-canonical URL redirect yourself before the SwaggerUI middleware is invoked. This will give you more control and should allow you to workaround any weird, edge case issues - i.e. like the AWS Gateway issue described above:

```csharp
app.UseRewriter(new RewriteOptions().AddRedirect("(.*)api/docs$", "$1api/docs/index.html"));

app.UseSwagger(c =>
{
    c.RouteTemplate = "api/docs/{documentName}/swagger.json";
});

app.UseSwaggerUI(c =>
{
    c.RoutePrefix = "api/docs";
    c.SwaggerEndpoint("v1/swagger.json", "My API (V1)");
});
```
