### ISSUE TITLE
No service for type 'Swashbuckle.AspNetCore.Swagger.ISwaggerProvider' has been registered.

### ISSUE THREAD

**Issue by seanmars** [domaindrivendev/Swashbuckle.AspNetCore#763]
.NET Core 2.1
Swashbuckle.AspNetCore 2.5.0
Swashbuckle.AspNetCore.Cli 2.5.0-beta1

When i build with cli, it's got the error `No service for type 'Swashbuckle.AspNetCore.Swagger.ISwaggerProvider' has been registered.`

**Comment by domaindrivendev** [comment]
Are you registering the service via `AddSwaggerGen` in your `Startup.cs`?

**Comment by seanmars** [comment]
Yes and i just run the  project of https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/master/test/Swashbuckle.AspNetCore.Cli.Test, but i'm use dotnet core 2.1

**Comment by PRIMETSS** [comment]
Had same issue if installed via NuGet UI Manager, get services.AddSwaggerGen() Unknow Ref!. 
But if installed via PM Console

Package Manager : Install-Package Swashbuckle.AspNetCore

Worked. Same version got installed 2.5.0

**Comment by domaindrivendev** [comment]
@seanmars are you still experiencing an issue with this?

**Comment by seanmars** [comment]
> @seanmars are you still experiencing an issue with this?

It seems to have been fixed, no longer encountered this issue.

**Comment by BlackRider97** [comment]
We are still facing the same issue (Net core 3.1, Swashbuckle.AspNetCore 5.5.0, Swashbuckle.AspNetCore.Cli 5.5.0)

```
Unhandled exception. System.InvalidOperationException: No service for type 'Swashbuckle.AspNetCore.Swagger.ISwaggerProvider' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 72
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 111
```

**Comment by SSanjeevi** [comment]
Facing Same for  (Net core 3.1, Swashbuckle.AspNetCore 5.5.0, Swashbuckle.AspNetCore.Cli 5.5.1)

**Comment by ruzgarustu** [comment]
I am experiencing the same with .Net 5, Swashbuckle.AspNetCore 6.2.3, Swashbuckle.AspNetCore.Cli 6.2.3
Is there a solution already? How did the members with this problem solve that? I am already registering the service via AddSwaggerGen.

**Comment by BenjaminAbt** [comment]
Same issue here. Both in my actual project and in a test project I get the identical error.

**Comment by BenjaminAbt** [comment]
I have found the bug, but I am not sure if it is a behavior by design or rather a design bug.

Our Startup class is very large and also has corresponding configuration validations, as recommended.
In our case, if no appsettings is set, certain config values are (deliberately) null, which cause our error in interaction with Swashbuckle.CLI.

This is because Swashbuckle tries to build the pipeline, and runs into an exception in our validations accordingly.
So it doesn't even get that far with us that AddSwaggerGen is executed - and unfortunately the CLI has no behavior that catches that.

For us, it is enough to define an alternative, minimal startup class.

```csharp
// https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/95cb4d370e08e54eb04cf14e7e6388ca974a686e/src/Swashbuckle.AspNetCore.Cli/Program.cs#L12
public static class SwaggerHostFactory
{
    public static IHost CreateHost()
    {
        return Host.CreateDefaultBuilder(new string[])
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<TStartup>();
            });
        .Build();
    }
}

public class SwaggerStartup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();
        services.AddSwaggerGen(options =>
        {
            options.SwaggerDoc("v1", new OpenApiInfo
            {
                Version = "v1",
                Title = "My API"
            });
        });
    }
}
```
